version: "3.8"

services:
  app:
    build: .
    container_name: course-stream-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: course-stream-db
    environment:
      POSTGRES_DB: back_office
      POSTGRES_USER: pedream
      POSTGRES_PASSWORD: 32357989
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
