spring.application.name=Edubyte

spring.datasource.url=jdbc:postgresql://localhost:5432/back_office
spring.datasource.username=pedream
spring.datasource.password=32357989

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true